version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  weather-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-service
    restart: always
    ports:
      - "7053:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDB: "mongodb://root:example@mongodb:27017"
      Database__Name: "WeatherServiceDb"
    depends_on:
      - mongodb

volumes:
  mongodb_data: